build:
  image: ubuntu-drone
  commands:
    - ./configure --disable-lhapdf
    - make
    - ./examples/Luminosity
    - ./examples/Tabulation < examples/input.txt
    - ./examples/SumRules < examples/input.txt
    - ./examples/DISObservables < examples/input.txt
    - ./examples/CheckAPFEL

notify:
  email:
    host: 127.0.0.1
    from: support@apfel.mi.infn.it
    recipients:
      - stefano.carrazza@cern.ch
      - valerio.bertone@cern.ch
