build:
  image: ubuntu-drone
  commands:
    - ./configure --disable-lhapdf
    - make
    - ./examples/Luminosity
    - ./examples/Tabulation < examples/input.txt
    - ./examples/SumRules < examples/input.txt
    - ./examples/DISObservables < examples/input.txt
    - ./examples/CheckAPFEL

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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 
    channel: general
    username: drone
  email:
    host: 0.0.0.0
    from: apfel@apfel.mi.infn.it
    recipients:
      - stefano.carrazza@cern.ch
      - valerio.bertone@cern.ch
