image: gcc
script:
   - sudo apt-get update
   - sudo apt-get install gfortran g++ make
   - ./configure --disable-lhapdf
   - make
   - ./examples/Luminosity
   - ./examples/Tabulation < examples/input.txt