build:
  image: ubuntu-drone
  commands:
    - ./configure --disable-lhapdf
    - make
    - ./examples/Luminosity
    - ./examples/Tabulation < examples/input.txt
    - ./examples/SumRules < examples/input.txt
    - ./examples/DISObservables < examples/input.txt
    - ./examples/CheckAPFEL

notify:
  gitter:    
    webhook:
      urls:
        - https://webhooks.gitter.im/e/c18c4fa359e51b9fa8be
      on_started: true
      on_success: true
      on_failure: true