sudo: false

addons:
  apt:
    packages:
      - gfortran
script: 
  - ./configure --disable-lhapdf && make
  - ./examples/Luminosity
  - ./examples/Tabulation < examples/input.txt
  - ./examples/SumRules < examples/input.txt
  - ./examples/DISObservables < examples/input.txt
  - ./examples/CheckAPFEL

notifications:
  email:
    - stefano.carrazza@cern.ch